version: '3.7'

services:
  bnb:
    container_name: bnb
    restart: unless-stopped
    build: .
    ports:
      - 27146:27146
      - 27147:27147
    volumes:
      - bnb:/var/lib/bnb/
    networks:
      - bnb
    environment:
      BNET: "prod"
    security_opt:
      - no-new-privileges
    ulimits:
      nofile:
        soft: 16000
        hard: 16000
    sysctls:
      net.core.somaxconn: 4096
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "1"

  bnb_testnet:
    container_name: bnb_testnet
    restart: unless-stopped
    build: .
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - bnb_testnet:/var/lib/bnb/
    networks:
      - bnb
    environment:
      BNET: "testnet"
    security_opt:
      - no-new-privileges
    ulimits:
      nofile:
        soft: 16000
        hard: 16000
    sysctls:
      net.core.somaxconn: 4096
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "1"

volumes:
  bnb:
  bnb_testnet:

networks:
  bnb:
